### ISSUE TITLE
missing TNS photometry

### ISSUE THREAD

**Issue by astrofoley** [davecoulter/YSE_PZ#48] opened 2020-07-21 18:14 UTC
https://ziggy.ucolick.org/yse/transient_detail/2020ptx/
https://wis-tns.weizmann.ac.il/object/2020ptx

**Comment by djones1040** [comment] 2020-07-25 05:39
bleh the observer uploaded the observation as flux unit = "other" so my code has no way of knowing it's a magnitude.  I think I'm going to close this out as "broken by design" though longer term it would be good to have a way of putting in photometry by hand.

**Closed by djones1040** 2020-07-25 05:39 UTC
